theme: jekyll-theme-slate
#title: "My Website"
#description: "My first website with minimal theme"
repository: "DmitrySemikin/open-neutral-mesh-file-formats"
show_downloads: false
#github: [metadata]
